require:
  - rubocop-rspec
  - rubocop-rails
  - rubocop-performance

AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - ".*"
    - "**/coverage/"
    - "bin/**/*"
    - "config/routes.rb"
    - "db/**/*"
    - "log/**/*"
    - "org/**/*"
    - "public/**/*"
    - "tmp/**/*"
    - "vendor/**/*"

Metrics/AbcSize:
  Max: 20

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 15

Style/Documentation:
  Enabled: false
 
