require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - '.*'
    - '**/coverage/'
    - 'bin/**/*'
    - 'config/routes.rb'
    - 'db/**/*'
    - 'log/**/*'
    - 'org/**/*'
    - 'public/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    
Metrics/LineLength:
  Max: 120
